export default {
    ADD_MORE_IN_CART: "ADD_MORE_IN_CART",
    MINUS_IN_CART: "MINUS_IN_CART",
    SAVE_TO_CART: "SAVE_TO_CART",
    KNOW_MORE: "KNOW_MORE",
    RECEIVE_DATA: "RECEIVE",
    WANT_DATA: "WANT_DATA"
}