export default {
    ADD_MORE_IN_CART: "ADD_MORE_IN_CART",
    MINUS_IN_CART: "MINUS_IN_CART",
    SAVE_TO_CART: "SAVE_TO_CART",
    KNOW_MORE: "KNOW_MORE",
    RECEIVE_DATA: "RECEIVE",
    WANT_DATA: "WANT_DATA",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    COMPLETE_ORDER: "COMPLETE_ORDER",
    SEND_ORDER: "SEND_ORDER",
    VALIDATE_USER: "VALIDATE_USER",
    CHANGE_USER: "CHANGE_USER",
    TOGGLE_MODAL_CART: "TOGGLE_MODAL_CART"
}